version: '3.10'
services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    restart: always
    env_file:
      - .env
    command: uvicorn apps.server.server:app --host 0.0.0.0 --port 5000
    ports:
      - 8000:5000

  loader:
    build:
      context: .
      dockerfile: docker/loader/Dockerfile
    restart: always
    env_file:
      - .env
    command: python3 start_loader.py

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    env_file:
      - .env

networks:
  default:
    driver: bridge


